try {
    console.log(a+b);
} catch (error) {
    console.log(error);

    console.log("error!");
}

// console.log(a+b);